# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('eslr-example', ['eslr', 'netanim', 'point-to-point', 'internet', 'network', 'applications'])
    obj.source = 'eslr-example.cc'

